# Canais
Channel.create(:name => "Agro Canal", :color => "#337ab7", :font => "#FFFFFF")
Channel.create(:name => "Canal do Boi", :color => "#388E3C", :font => "#FFFFFF")
Channel.create(:name => "Canal Rural", :color => "#795548", :font => "#FFFFFF")
Channel.create(:name => "Novo Canal", :color => "#E91E63", :font => "#FFFFFF")
Channel.create(:name => "Terra Viva", :color => "#FF9800", :font => "#212121")
Channel.create(:name => "Sem Transmissão", :color => "#9E9E9E", :font => "#212121")

# Feriados
Holiday.create(:name => 'Ano Novo', :date => '2016-01-01', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Carnaval', :date => '2016-02-05', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Carnaval', :date => '2016-02-06', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Carnaval', :date => '2016-02-07', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Carnaval', :date => '2016-02-08', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Carnaval', :date => '2016-02-09', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-03-24', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-03-29', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-09-02', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-09-06', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-10-07', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-10-11', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-11-11', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Jogo do Brasil', :date => '2016-11-15', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Sexta-feira da Paixão', :date => '2016-03-25', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Páscoa', :date => '2016-03-27', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Tiradentes', :date => '2016-04-21', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Dia do Trabalho', :date => '2016-05-01', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Corpus Christi', :date => '2016-05-26', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Independência do Brasil', :date => '2016-09-07', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Nossa Senhora Aparecida', :date => '2016-10-12', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Finados', :date => '2016-11-02', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Proclamação da República', :date => '2016-11-15', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Natal', :date => '2016-12-25', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Eleições', :date => '2016-10-02', :color => '#9C27B0', :font => '#FFFFFF')
Holiday.create(:name => 'Eleições', :date => '2016-10-30', :color => '#9C27B0', :font => '#FFFFFF')

# Usuários - Admin
User.create(username: 'admin', email: '', password: 'agenda123', password_confirmation: 'agenda123', :admin => 1)
User.create(username: 'fabiana@centralleiloes.com.br', email: '', password: '100senha', password_confirmation: '100senha', :admin => 1)

# Usuários - Padrão
User.create(username: 'adm.secretaria@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'adriana@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'antonio.comercial@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'atendimento1@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'atendimento2@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'atendimento3@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'auditoria@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'cadastros@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'cpd1@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'User.create(username: cpd2@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'cpd3@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'cpd4@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'fabio@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'financeiro@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'financeiro2@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'financeiro3@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'guilherme.comercial@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'jaqueline@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'joao@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'katia@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'larissa@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'leiloes@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'leiloes1@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'leiloes2@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'leiloes4@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'leiloes5@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'lourenco@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'lucas@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'lucianafernandes@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'pedro@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'ricardo@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)
User.create(username: 'telemarketing@centralleiloes.com.br', email: '', password: 'agendacentral123', password_confirmation: 'agendacentral123', :admin => 0)

# Leilões - 2016 (25/01/2016)
Meeting.create(name: 'LEILÃO VIRTUAL QUALIDADE TOTAL',description: 'LEILÃO VIRTUAL QUALIDADE TOTAL', channel_id: 2, place: 'Virtual', start_time: '2016-01-30 14:00:00')
Meeting.create(name: 'LEILÃO SOLIDARIEDADE 2016',description: 'LEILÃO SOLIDARIEDADE 2016', channel_id: 1, place: 'Araçatuba/SP', start_time: '2016-02-21 14:00:00')
Meeting.create(name: 'DIA DE CAMPO NELORE DO GOLIAS',description: 'DIA DE CAMPO NELORE DO GOLIAS', channel_id: 2, place: 'Araçatuba/SP', start_time: '2016-02-27 10:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL QUALIDADE TOTAL',description: 'LEILÃO VIRTUAL QUALIDADE TOTAL', channel_id: 2, place: 'Virtual', start_time: '2016-02-27 14:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-03-03 18:40:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-03-10 18:40:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-03-17 18:40:00')
Meeting.create(name: '2° LEILÃO VIRTUAL EULER MIRANDA',description: '2° LEILÃO VIRTUAL EULER MIRANDA', channel_id: 5, place: 'Virtual', start_time: '2016-03-18 21:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL QUALIDADE TOTAL',description: 'LEILÃO VIRTUAL QUALIDADE TOTAL', channel_id: 2, place: 'Virtual', start_time: '2016-03-20 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL SANTA MARINA',description: 'LEILÃO VIRTUAL SANTA MARINA', channel_id: 3, place: 'Virtual', start_time: '2016-03-20 21:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-03-24 18:40:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-03-31 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL TABAPUÃ TRO',description: 'LEILÃO VIRTUAL TABAPUÃ TRO', channel_id: 2, place: 'Virtual', start_time: '2016-03-31 20:00:00')
Meeting.create(name: 'LEILÃO NOVILHA DO FUTURO',description: 'LEILÃO NOVILHA DO FUTURO', channel_id: 6, place: 'Tietê/SP', start_time: '2016-04-02 14:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-04-07 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL HARAS VERSÁTIL',description: 'LEILÃO VIRTUAL HARAS VERSÁTIL', channel_id: 2, place: 'Virtual', start_time: '2016-04-10 14:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-04-14 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUOSO DO CÓRREGO',description: 'LEILÃO VIRTUOSO DO CÓRREGO', channel_id: 2, place: 'Virtual', start_time: '2016-04-19 20:00:00')
Meeting.create(name: 'LEILÃO NELORE CEN',description: 'LEILÃO NELORE CEN', channel_id: 2, place: 'Valparaiso/SP', start_time: '2016-04-23 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL QUALIDADE TOTAL',description: 'LEILÃO VIRTUAL QUALIDADE TOTAL', channel_id: 2, place: 'Virtual', start_time: '2016-04-24 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL FAZENDA MUTENA',description: 'LEILÃO VIRTUAL FAZENDA MUTENA', channel_id: 2, place: 'Virtual', start_time: '2016-04-25 20:00:00')
Meeting.create(name: 'EXPÔ ZEBU - LEILÃO SÊMEN ADIR',description: 'EXPÔ ZEBU - LEILÃO SÊMEN ADIR', channel_id: 2, place: 'Virtual', start_time: '2016-04-29 20:00:00')
Meeting.create(name: 'EXPÔ ZEBU - LEILÃO ÁGUA MILAGROSA',description: 'EXPÔ ZEBU - LEILÃO ÁGUA MILAGROSA', channel_id: 2, place: 'Virtual', start_time: '2016-04-30 20:00:00')
Meeting.create(name: 'EXPÔ ZEBU - LEILÃO TABAPUÃ RENATO FERNANDES',description: 'EXPÔ ZEBU - LEILÃO TABAPUÃ RENATO FERNANDES', channel_id: 6, place: '', start_time: '2016-05-01 20:00:00')
Meeting.create(name: 'EXPÔ ZEBU - LEILÃO ABCT',description: 'EXPÔ ZEBU - LEILÃO ABCT', channel_id: 2, place: 'Virtual', start_time: '2016-05-02 20:00:00')
Meeting.create(name: 'EXPÔ ZEBU - LEILÃO ADIR',description: 'EXPÔ ZEBU - LEILÃO ADIR', channel_id: 2, place: 'Virtual', start_time: '2016-05-03 18:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-05-05 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL PECUÁRIA BR',description: 'LEILÃO VIRTUAL PECUÁRIA BR', channel_id: 2, place: 'Virtual', start_time: '2016-05-07 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL NELORE CEN SINDI',description: 'LEILÃO VIRTUAL NELORE CEN SINDI', channel_id: 2, place: 'Virtual', start_time: '2016-05-09 20:00:00')
Meeting.create(name: 'LEILÃO SENEPOL 3G',description: 'LEILÃO SENEPOL 3G', channel_id: 2, place: 'Barretos/SP', start_time: '2016-05-10 20:00:00')
Meeting.create(name: 'LEILÃO SENEPOL 3G',description: 'LEILÃO SENEPOL 3G', channel_id: 2, place: 'Barretos/SP', start_time: '2016-05-11 20:00:00')
Meeting.create(name: 'LEILÃO SENEPOL 3G',description: 'LEILÃO SENEPOL 3G', channel_id: 2, place: 'Barretos/SP', start_time: '2016-05-12 20:00:00')
Meeting.create(name: 'LEILÃO SENEPOL 3G',description: 'LEILÃO SENEPOL 3G', channel_id: 2, place: 'Barretos/SP', start_time: '2016-05-13 20:00:00')
Meeting.create(name: 'LEILÃO SENEPOL 3G',description: 'LEILÃO SENEPOL 3G', channel_id: 1, place: 'Barretos/SP', start_time: '2016-05-14 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL HARAS VERSÁTIL TROPA',description: 'LEILÃO VIRTUAL HARAS VERSÁTIL TROPA', channel_id: 4, place: 'Virtual', start_time: '2016-05-15 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL WILSON LEMOS',description: 'LEILÃO VIRTUAL WILSON LEMOS', channel_id: 2, place: 'Virtual', start_time: '2016-05-16 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-05-19 18:40:00')
Meeting.create(name: 'LEILÃO ÔNIX',description: 'LEILÃO ÔNIX', channel_id: 2, place: 'Três Lagoas/MS', start_time: '2016-05-21 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MARCA SOL',description: 'LEILÃO VIRTUAL MARCA SOL', channel_id: 2, place: 'Virtual', start_time: '2016-05-24 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-05-26 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL ALGE SENEPOL',description: 'LEILÃO VIRTUAL ALGE SENEPOL', channel_id: 2, place: 'Virtual', start_time: '2016-05-26 20:00:00')
Meeting.create(name: 'LEILÃO TRIO BOM SUCESSO REPRODUTORES',description: 'LEILÃO TRIO BOM SUCESSO REPRODUTORES', channel_id: 2, place: 'Guararapes/SP', start_time: '2016-05-28 14:00:00')
Meeting.create(name: 'LEILÃO TRIO BOM SUCESSO MATRIZES',description: 'LEILÃO TRIO BOM SUCESSO MATRIZES', channel_id: 2, place: 'Guararapes/SP', start_time: '2016-05-29	14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL HARAS VERSÁTIL',description: 'LEILÃO VIRTUAL HARAS VERSÁTIL', channel_id: 2, place: 'Virtual', start_time: '2016-05-30	20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL HARAS VERSÁTIL',description: 'LEILÃO VIRTUAL HARAS VERSÁTIL', channel_id: 2, place: 'Virtual', start_time: '2016-05-31	20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-06-02 18:40:00')
Meeting.create(name: 'LEILÃO BARTIRA',description: 'LEILÃO BARTIRA', channel_id: 2, place: 'Rancharia/SP', start_time: '2016-06-04 14:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-06-09 18:40:00')
Meeting.create(name: 'LEILÃO Q12',description: 'LEILÃO Q12', channel_id: 2, place: 'Três Lagoas/MS', start_time: '2016-06-10 20:00:00')
Meeting.create(name: '4° LEILÃO CHATEAUBRIAND',description: '4° LEILÃO CHATEAUBRIAND', channel_id: 2, place: 'Virtual', start_time: '2016-06-13 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-06-16 18:40:00')
Meeting.create(name: 'LEILÃO BARTIRA',description: 'LEILÃO BARTIRA', channel_id: 1, place: 'Canápoli/MG', start_time: '2016-06-18 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MAXI CORTE',description: 'LEILÃO VIRTUAL MAXI CORTE', channel_id: 2, place: 'Virtual', start_time: '2016-06-19 14:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-06-23 18:40:00')
Meeting.create(name: 'LEILÃO NELORE JANDAIA',description: 'LEILÃO NELORE JANDAIA', channel_id: 2, place: 'Barra do Garças/MT', start_time: '2016-06-25 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL GUZERÁ TRÊS IRMÃOS',description: 'LEILÃO VIRTUAL GUZERÁ TRÊS IRMÃOS', channel_id: 2, place: 'Virtual', start_time: '2016-06-27 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-06-30 18:40:00')
Meeting.create(name: 'LEILÃO TERRA BOA',description: 'LEILÃO TERRA BOA', channel_id: 3, place: 'Guararapes/SP', start_time: '2016-07-03 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL FAGANELLO',description: 'LEILÃO VIRTUAL FAGANELLO', channel_id: 5, place: 'Virtual', start_time: '2016-07-04 20:00:00')
Meeting.create(name: 'LEILÃO ÁGUA MILAGROSA',description: 'LEILÃO ÁGUA MILAGROSA', channel_id: 2, place: 'Cuiabá/MT', start_time: '2016-07-06 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-07-07 18:40:00')
Meeting.create(name: 'LEILÃO BRAHMAN',description: 'LEILÃO BRAHMAN', channel_id: 6, place: 'Rio de Janeiro/RJ', start_time: '2016-07-08 14:00:00')
Meeting.create(name: 'LEILÃO TABAPUÃ BRUNO GREGG',description: 'LEILÃO BRAHMAN', channel_id: 6, place: 'Rio de Janeiro/RJ', start_time: '2016-07-09 14:00:00')
Meeting.create(name: 'LEILÃO NELORE GUTO GRASSANO',description: 'LEILÃO NELORE GUTO GRASSANO', channel_id: 2, place: 'Coxim/MS', start_time: '2016-07-09 14:00:00')
Meeting.create(name: 'RESERVA MARCA LI',description: 'RESERVA MARCA LI', channel_id: 2, place: 'Coxim/MS', start_time: '2016-07-10 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL AGRO LONDRINA',description: 'LEILÃO VIRTUAL AGRO LONDRINA', channel_id: 2, place: 'Virtual', start_time: '2016-07-11 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MARCA SOL',description: 'LEILÃO VIRTUAL MARCA SOL', channel_id: 2, place: 'Virtual', start_time: '2016-07-12 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-07-14 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL TESOURO EAO',description: 'LEILÃO VIRTUAL TESOURO EAO', channel_id: 2, place: 'Virtual', start_time: '2016-07-16 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL FÊMEAS EAO',description: 'LEILÃO VIRTUAL FÊMEAS EAO', channel_id: 2, place: 'Virtual', start_time: '2016-07-17 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL COPACABANA',description: 'LEILÃO VIRTUAL COPACABANA', channel_id: 2, place: 'Virtual', start_time: '2016-07-18 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL NELORE DP',description: 'LEILÃO VIRTUAL NELORE DP', channel_id: 2, place: 'Virtual', start_time: '2016-07-19 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-07-21 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL ESPECIAL DE TOUROS',description: 'LEILÃO VIRTUAL ESPECIAL DE TOUROS', channel_id: 2, place: 'Virtual', start_time: '2016-07-23 14:00:00')
Meeting.create(name: 'LEILÃO AGRO JACAREZINHO',description: 'LEILÃO AGRO JACAREZINHO', channel_id: 1, place: 'Cotegipe/BA', start_time: '2016-07-24 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL SENEPOL CMI',description: 'LEILÃO VIRTUAL SENEPOL CMI', channel_id: 2, place: 'Virtual', start_time: '2016-07-25 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-07-28 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL GRUPO REZENDE',description: 'LEILÃO VIRTUAL GRUPO REZENDE', channel_id: 2, place: 'Virtual', start_time: '2016-07-28 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL BELA ALVORADA',description: 'LEILÃO VIRTUAL BELA ALVORADA', channel_id: 2, place: 'Virtual', start_time: '2016-07-30 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ATALLA',description: 'LEILÃO VIRTUAL ATALLA', channel_id: 2, place: 'Virtual', start_time: '2016-07-31 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ÁGUA MILAGROSA',description: 'LEILÃO VIRTUAL ÁGUA MILAGROSA', channel_id: 2, place: 'Virtual', start_time: '2016-08-03 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ÁGUA MILAGROSA',description: 'LEILÃO VIRTUAL ÁGUA MILAGROSA', channel_id: 2, place: 'Virtual', start_time: '2016-08-04 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-08-04 18:40:00')
Meeting.create(name: 'MEGA LEILÃO FÊMEAS CFM',description: 'MEGA LEILÃO FÊMEAS CFM', channel_id: 2, place: 'São José do Rio Preto/SP', start_time: '2016-08-10 20:00:00')
Meeting.create(name: 'MEGA LEILÃO TOUROS CFM',description: 'MEGA LEILÃO TOUROS CFM', channel_id: 2, place: 'São José do Rio Preto/SP', start_time: '2016-08-11 10:00:00')
Meeting.create(name: 'MEGA LOJA CFM',description: 'MEGA LOJA CFM', channel_id: 2, place: 'Magda/SP', start_time: '2016-08-12 07:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MEGA MONTANA',description: 'LEILÃO VIRTUAL MEGA MONTANA', channel_id: 2, place: 'Virtual', start_time: '2016-08-16 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL TULIPA',description: 'LEILÃO VIRTUAL TULIPA', channel_id: 2, place: 'Virtual', start_time: '2016-08-17 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL TULIPA',description: 'LEILÃO VIRTUAL TULIPA', channel_id: 2, place: 'Virtual', start_time: '2016-08-18 14:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-08-18 18:40:00')
Meeting.create(name: '17° LEILÃO KATAYAMA',description: '17° LEILÃO KATAYAMA', channel_id: 3, place: 'Guararapes/SP', start_time: '2016-08-20 14:00:00')
Meeting.create(name: 'EXPÔ GENÉTICA - LEILÃO BOI COM BULA',description: 'EXPÔ GENÉTICA - LEILÃO BOI COM BULA', channel_id: 5, place: 'Virtual', start_time: '2016-08-22 20:00:00')
Meeting.create(name: 'EXPÔ GENÉTICA - LEILÃO VIRTUAL KATAYAMA',description: 'EXPÔ GENÉTICA - LEILÃO VIRTUAL KATAYAMA', channel_id: 2, place: 'Virtual', start_time: '2016-08-23 20:00:00')
Meeting.create(name: 'EXPÔ GENÉTICA - LEILÃO AC MERCANTIL',description: 'EXPÔ GENÉTICA - LEILÃO AC MERCANTIL', channel_id: 5, place: 'Virtual', start_time: '2016-08-24 21:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-08-25 18:40:00')
Meeting.create(name: 'EXPÔ GENÉTICA - LEILÃO VIRTUAL NELORE CEN',description: 'EXPÔ GENÉTICA - LEILÃO VIRTUAL NELORE CEN', channel_id: 2, place: 'Virtual', start_time: '2016-08-25 20:00:00')
Meeting.create(name: 'EXPÔ GENÉTICA - LEILÃO VIRTUAL NELORE BIO',description: 'EXPÔ GENÉTICA - LEILÃO VIRTUAL NELORE BIO', channel_id: 2, place: 'Virtual', start_time: '2016-08-26 20:00:00')
Meeting.create(name: 'EXPÔ GENÉTICA - LEILÃO COLONIAL',description: 'EXPÔ GENÉTICA - LEILÃO COLONIAL', channel_id: 2, place: 'Virtual', start_time: '2016-08-27 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL NELORE DS',description: 'LEILÃO VIRTUAL NELORE DS', channel_id: 2, place: 'Virtual', start_time: '2016-08-29 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MARCA SOL',description: 'LEILÃO VIRTUAL MARCA SOL', channel_id: 2, place: 'Virtual', start_time: '2016-08-30 20:00:00')
Meeting.create(name: '10° LEILÃO VIRTUAL PAINT',description: '10° LEILÃO VIRTUAL PAINT', channel_id: 2, place: 'Sertãozinho/SP', start_time: '2016-08-31 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-09-01 18:40:00')
Meeting.create(name: 'LEILÃO NELORE HORA',description: 'LEILÃO NELORE HORA', channel_id: 2, place: 'Cornélio Procópio/PR', start_time: '2016-09-01 20:00:00')
Meeting.create(name: 'LEILÃO NELORE HORA',description: 'LEILÃO NELORE HORA', channel_id: 2, place: 'Cornélio Procópio/PR', start_time: '2016-09-02 20:00:00')
Meeting.create(name: 'LEILÃO NELORE HORA',description: 'LEILÃO NELORE HORA', channel_id: 2, place: 'Cornélio Procópio/PR', start_time: '2016-09-03 20:00:00')
Meeting.create(name: 'LEILÃO CARPA',description: 'LEILÃO CARPA', channel_id: 3, place: 'Barra do Garças/MT', start_time: '2016-09-04 10:00:00')
Meeting.create(name: 'LEILÃO UFU',description: 'LEILÃO UFU', channel_id: 2, place: 'Uberlândia/MG', start_time: '2016-09-04 14:00:00')
Meeting.create(name: 'LEILÃO IZ',description: 'LEILÃO IZ', channel_id: 2, place: 'Sertãozinho/SP', start_time: '2016-09-08 14:00:00')
Meeting.create(name: 'LEILÃO TOUROS SANTA MARTINA',description: 'LEILÃO TOUROS SANTA MARTINA', channel_id: 3, place: 'Virtual', start_time: '2016-09-08 21:00:00')
Meeting.create(name: 'LEILÃO TOUROS FAZENDA BOSMARA',description: 'LEILÃO FAZENDA BOSMARA', channel_id: 1, place: 'Virtual', start_time: '2016-09-10 14:00:00')
Meeting.create(name: 'LEILÃO BRANGUS PRUDENTE',description: 'LEILÃO BRANGUS PRUDENTE', channel_id: 6, place: 'Presidente Prudente/SP', start_time: '2016-09-11 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ALGE SENEPOL',description: 'LEILÃO VIRTUAL ALGE SENEPOL', channel_id: 2, place: 'Virtual', start_time: '2016-09-11 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL VANGUARDA',description: 'LEILÃO VIRTUAL VANGUARDA', channel_id: 2, place: 'Virtual', start_time: '2016-09-12 20:00:00')
Meeting.create(name: '21° LEILÃO VIRTUAL BERÇO DO TABAPUÃ',description: '21° LEILÃO VIRTUAL BERÇO DO TABAPUÃ', channel_id: 2, place: 'Virtual', start_time: '2016-09-13 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-09-15 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL CONEXÃO DELTA GEN',description: 'LEILÃO VIRTUAL CONEXÃO DELTA GEN', channel_id: 2, place: 'Virtual', start_time: '2016-09-15 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL FAZENDA NOVA',description: 'LEILÃO VIRTUAL FAZENDA NOVA', channel_id: 2, place: 'Virtual', start_time: '2016-09-17 14:00:00')
Meeting.create(name: 'LEILÃO FAZENDA SANTANA',description: 'LEILÃO FAZENDA SANTANA', channel_id: 5, place: 'Rancharia/SP', start_time: '2016-09-18 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ÁGUA DOCE',description: 'LEILÃO VIRTUAL ÁGUA DOCE', channel_id: 2, place: 'Virtual', start_time: '2016-09-19 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-09-22 18:40:00')
Meeting.create(name: '16° LEILÃO BRANGUS JMT',description: '16° LEILÃO BRANGUS JMT', channel_id: 3, place: 'Santa Maria/RS', start_time: '2016-09-22 14:00:00')
Meeting.create(name: 'LEILÃO RAÇAS BRITÂNICAS',description: 'LEILÃO RAÇAS BRITÂNICAS', channel_id: 6, place: 'Bauru/SP', start_time: '2016-09-24 14:00:00')
Meeting.create(name: 'LEILÃO SÃO XAVIER',description: 'LEILÃO SÃO XAVIER', channel_id: 3, place: 'Santa Maria/RS', start_time: '2016-09-26 14:00:00')
Meeting.create(name: 'RESERVA',description: 'RESERVA', channel_id: 2, place: 'Virtual', start_time: '2016-09-26 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MOCHO BRASIL',description: 'LEILÃO VIRTUAL MOCHO BRASIL', channel_id: 2, place: 'Virtual', start_time: '2016-09-27 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL OURO BRANCO',description: 'LEILÃO VIRTUAL OURO BRANCO', channel_id: 2, place: 'Virtual', start_time: '2016-09-28 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-09-29 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL NELORE CEN',description: 'LEILÃO VIRTUAL NELORE CEN', channel_id: 2, place: 'Virtual', start_time: '2016-10-01 14:00:00')
Meeting.create(name: 'LEILÃO REPRODUTORES SENEPOL 3G',description: 'LEILÃO REPRODUTORES SENEPOL 3G', channel_id: 2, place: 'Barretos/SP', start_time: '2016-10-04 20:00:00')
Meeting.create(name: 'LEILÃO BABY SENEPOL',description: 'LEILÃO BABY SENEPOL', channel_id: 2, place: 'Barretos/SP', start_time: '2016-10-05 20:00:00')
Meeting.create(name: 'LEILÃO ALIANÇA SENEPOL',description: 'LEILÃO ALIANÇA SENEPOL', channel_id: 2, place: 'Barretos/SP', start_time: '2016-10-06 20:00:00')
Meeting.create(name: 'LEILÃO DO ADIR',description: 'LEILÃO DO ADIR', channel_id: 2, place: 'Nova Crixás/GO', start_time: '2016-10-08 10:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL NELORE DP',description: 'LEILÃO VIRTUAL NELORE DP', channel_id: 2, place: 'Virtual', start_time: '2016-10-09 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL CFM',description: 'LEILÃO VIRTUAL CFM', channel_id: 2, place: 'Virtual', start_time: '2016-10-10 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-10-13 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL NELORE BEKA',description: 'LEILÃO VIRTUAL NELORE BEKA', channel_id: 2, place: 'Virtual', start_time: '2016-10-18 20:00:00')
Meeting.create(name: 'GUATAMBU/ALVORADA/CATY',description: 'GUATAMBU/ALVORADA/CATY', channel_id: 3, place: 'Dom Pedrito/RS', start_time: '2016-10-20 10:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-10-20 18:40:00')
Meeting.create(name: 'LEILÃO CONEXÃO PAMPA',description: 'LEILÃO CONEXÃO PAMPA', channel_id: 2, place: 'Alegrete/RS', start_time: '2016-10-22 18:00:00')
Meeting.create(name: 'RESERVA ALEGRETE',description: 'RESERVA ALEGRETE', channel_id: 1, place: 'Virtual', start_time: '2016-10-23 14:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ALGE SENEPOL',description: 'LEILÃO VIRTUAL ALGE SENEPOL', channel_id: 2, place: 'Virtual', start_time: '2016-10-25 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-11-03 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL CFM',description: 'LEILÃO VIRTUAL CFM', channel_id: 2, place: 'Virtual', start_time: '2016-11-07 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL ÁGUA MILAGROSA',description: 'LEILÃO VIRTUAL ÁGUA MILAGROSA', channel_id: 2, place: 'Virtual', start_time: '2016-11-08 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-11-10 18:40:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-11-17 18:40:00')
Meeting.create(name: '4° LEILÃO VIRTUAL TAB PRODUÇÃO',description: '4° LEILÃO VIRTUAL TAB PRODUÇÃO', channel_id: 2, place: 'Virtual', start_time: '2016-11-22 20:00:00')
Meeting.create(name: 'ESTAÇÃO CENTRAL',description: 'ESTAÇÃO CENTRAL', channel_id: 1, place: 'Virtual', start_time: '2016-11-24 18:40:00')
Meeting.create(name: 'LEILÃO VIRTUAL ALGE SENEPOL',description: 'LEILÃO VIRTUAL ALGE SENEPOL', channel_id: 2, place: 'Virtual', start_time: '2016-11-24 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL AGRO JACAREZINHO',description: 'LEILÃO VIRTUAL AGRO JACAREZINHO', channel_id: 2, place: 'Virtual', start_time: '2016-11-28 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL CP LAGOA',description: 'LEILÃO VIRTUAL CP LAGOA', channel_id: 2, place: 'Virtual', start_time: '2016-12-03 20:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MASTER 12',description: 'LEILÃO VIRTUAL MASTER 12', channel_id: 2, place: 'Virtual', start_time: '2016-12-04 10:00:00')
Meeting.create(name: 'LEILÃO VIRTUAL MASTER 12',description: 'LEILÃO VIRTUAL MASTER 12', channel_id: 2, place: 'Virtual', start_time: '2016-12-05 20:00:00')